---

- name: Merge default variable
  ansible.builtin.import_tasks: merge-defaults.yml
  tags:
    - default
    - backups-only
    - config-only


- name: Setup Snipe-IT
  block:

    - ansible.builtin.import_tasks: version-check.yml
      tags: config-only

    - ansible.builtin.import_tasks: database.yml
      tags: config-only

    - ansible.builtin.import_tasks: restore.yml
      when:
        - snipeit_restore.overwrite | bool
        - snipeit_restore.timestamp != ""

    # not needed when restoring from backup
    - ansible.builtin.import_tasks: install.yml
      when: not (snipeit_restore.overwrite | bool)

    # not needed when restoring from backup
    - ansible.builtin.import_tasks: config.yml
      when: not (snipeit_restore.overwrite | bool)
      tags: config-only

    - ansible.builtin.import_tasks: vhost.yml
      tags: config-only

    - ansible.builtin.import_tasks: migrations.yml
      tags: config-only

    # note that you can skip the backup by setting
    # snipeit_restore.overwrite=False (just take care not to set .timestamp at the same time)
    - name: Backup the database and the working directory
      ansible.builtin.import_tasks: backup.yml
      # to ensure backup does not execute when restore just occurred
      # (simply because it is unnecessary, nothing dangerous would happen if it did)
      when: not (snipeit_restore.overwrite | bool)
      tags: backups-only
  # END OF BLOCK


- ansible.builtin.import_tasks: log-git-state.yml
  tags:
    - log-git-state
    - config-only
    - backups-only
