---

- name: restart apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: "{{ apache_restart_state }}"

- name: reload apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: "{{ apache_reload_state }}"

# Cleanup (remove) the decrypted database backup on the Ansible controller
- name: Remove the decrypted database backup
  delegate_to: localhost
  become: true
  become_user: "{{ ansible_env.USER }}"
  ansible.builtin.file:
    path: "{{ snipeit_backup_dir }}/{{ snipeit.database.name }}.sql.gz"
    state: absent

# Cleanup (remove) the decrypted workingdir backup on the Ansible controller
- name: Remove the decrypted tarball backup
  delegate_to: localhost
  become: true
  become_user: "{{ ansible_env.USER }}"
  ansible.builtin.file:
    path: "{{ snipeit_backup_dir }}/{{ role_name }}_files.tar"
    state: absent
